networks:
  vitals-network:
    driver: bridge
services:
  vitals-gcs:
    build: .
    image: gersh01/vitals-gcs:latest
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    ports:
      - "8000:8000"
    networks:
      - vitals-network
    command: ["python3", "missionState.py"]
