version: "3.9"

services:
  osm:
    image: overv/openstreetmap-tile-server
    container_name: vitals-osm-server
    ports:
      - "8080:80"
      - "5432:5432"
    environment:
      THREADS: 24
      OSM2PGSQL_EXTRA_ARGS: "-C 24000"
      BACKGROUND_RENDERING: "true"
      POSTGRES_USER: renderer
      POSTGRES_PASSWORD: renderer
    volumes:
      - osm-data:/data/database
      - osm-tiles:/data/tiles
    shm_size: "8gb"
    command: run

volumes:
  osm-data:
  osm-tiles:
